/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package importarset;

import common.Cargar;
import common.ScriptSql;
import common.Tools;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import org.postgresql.ds.PGSimpleDataSource;

/**
 *
 * @author josec
 */
public class Importar extends javax.swing.JFrame {

    /**
     * Creates new form Importar
     */
    DefaultTableModel modelo;
    long c = 0;
    DecimalFormat formato = new DecimalFormat();
    private Connection conexion = null;
    public ResultSet resultado = null;
    Cargar hilo;

    public Importar() {
        initComponents();
        modelo = (DefaultTableModel) jtContribuyente.getModel();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

//Le indicamos el filtro
        seleccionador.setFileFilter(filtro);
        ruta.setText("");
        cant.setText("0");
        record.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selector = new javax.swing.JDialog();
        seleccionador = new javax.swing.JFileChooser();
        modal = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDatabase = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnConectar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        ruta = new javax.swing.JTextField();
        btnAbrirTxt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtContribuyente = new javax.swing.JTable();
        btnExecute = new javax.swing.JButton();
        Progreso = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        cbTipoPersona = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        record = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbDelimiter = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        selector.setModal(true);
        selector.setSize(new java.awt.Dimension(643, 427));

        seleccionador.setApproveButtonText("Seleccionar Archivo SET");
        seleccionador.setDialogTitle("Seleccionar");
        seleccionador.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans-11.2\\*.txt"));
        seleccionador.setToolTipText("");
        seleccionador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectorLayout = new javax.swing.GroupLayout(selector.getContentPane());
        selector.getContentPane().setLayout(selectorLayout);
        selectorLayout.setHorizontalGroup(
            selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectorLayout.createSequentialGroup()
                .addComponent(seleccionador, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        selectorLayout.setVerticalGroup(
            selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        modal.setModal(true);
        modal.setSize(new java.awt.Dimension(300, 129));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>\n<center>\n<p><b>Aguarde</b></p><br>\n<p><b>un momento!</b></p>\n</center>\n</html>");

        javax.swing.GroupLayout modalLayout = new javax.swing.GroupLayout(modal.getContentPane());
        modal.getContentPane().setLayout(modalLayout);
        modalLayout.setHorizontalGroup(
            modalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        modalLayout.setVerticalGroup(
            modalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLACK Dwarf System Import::::::::::");
        setExtendedState(6);

        jLabel1.setText("Host Database:");

        txtHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHostKeyTyped(evt);
            }
        });

        jLabel2.setText("Port:");

        txtPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPortKeyTyped(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Database:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");

        txtDatabase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatabaseKeyTyped(evt);
            }
        });

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        btnConectar.setText("Connect");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Route:");

        ruta.setEditable(false);
        ruta.setBackground(new java.awt.Color(255, 255, 255));

        btnAbrirTxt.setText("Open File");
        btnAbrirTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirTxtActionPerformed(evt);
            }
        });

        jtContribuyente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "DV", "RAZON SOCIAL", "type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtContribuyente.setRowHeight(20);
        jScrollPane1.setViewportView(jtContribuyente);
        if (jtContribuyente.getColumnModel().getColumnCount() > 0) {
            jtContribuyente.getColumnModel().getColumn(0).setMinWidth(100);
            jtContribuyente.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtContribuyente.getColumnModel().getColumn(0).setMaxWidth(100);
            jtContribuyente.getColumnModel().getColumn(1).setMinWidth(50);
            jtContribuyente.getColumnModel().getColumn(1).setPreferredWidth(50);
            jtContribuyente.getColumnModel().getColumn(1).setMaxWidth(50);
            jtContribuyente.getColumnModel().getColumn(3).setMinWidth(0);
            jtContribuyente.getColumnModel().getColumn(3).setPreferredWidth(0);
            jtContribuyente.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        btnExecute.setText("Execute Import");
        btnExecute.setEnabled(false);
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        Progreso.setStringPainted(true);

        jLabel6.setText("Type Data Import:");

        cbTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Física", "Persona Jurídica" }));
        cbTipoPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbTipoPersonaKeyTyped(evt);
            }
        });

        jLabel7.setText("Cantidad:");

        cant.setEditable(false);
        cant.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Record:");

        record.setEditable(false);
        record.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Delimiter:");

        cbDelimiter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "Tab" }));
        cbDelimiter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbDelimiterKeyTyped(evt);
            }
        });

        btnClear.setText("Clear Table");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("User:");

        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });

        jMenu1.setText("Options");

        jMenuItem1.setText("Calcular Dígito Verificador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Exportar a Excel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Progreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExecute))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPort, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDatabase, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConectar))
                                    .addComponent(txtHost))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbTipoPersona, 0, 133, Short.MAX_VALUE)
                                    .addComponent(txtUser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDelimiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAbrirTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPass)
                        .addComponent(btnConectar)
                        .addComponent(jLabel6)
                        .addComponent(cbTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(cbDelimiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExecute)
                    .addComponent(Progreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionadorActionPerformed
        JFileChooser selectorArchivo = (JFileChooser) evt.getSource();
        //Creamos el filtro

        String command = evt.getActionCommand();
        if (command.equals(JFileChooser.APPROVE_SELECTION)) {
            File archivoSeleccionado = selectorArchivo.getSelectedFile();
            ruta.setText(archivoSeleccionado.getAbsolutePath());
            selector.dispose();

            creatArr();

        } else {
            if (command.equals(JFileChooser.CANCEL_SELECTION)) {
                selector.dispose();
            }
        }
    }//GEN-LAST:event_seleccionadorActionPerformed

    private void btnAbrirTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirTxtActionPerformed
        selector.setVisible(true);
    }//GEN-LAST:event_btnAbrirTxtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CalcularDv(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Tools.exportarExcel(jtContribuyente);
        } catch (IOException ex) {
            Logger.getLogger(Importar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        for (int i = jtContribuyente.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        c = 0;
        ruta.setText("");
        cant.setText("0");
        record.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        if (validar())
            conexion();
    }//GEN-LAST:event_btnConectarActionPerformed

    private void txtHostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            txtPort.requestFocus();
        }
    }//GEN-LAST:event_txtHostKeyTyped

    private void txtPortKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPortKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            txtDatabase.requestFocus();
        }
        if (!Character.isDigit(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPortKeyTyped

    private void txtDatabaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatabaseKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            txtUser.requestFocus();
        }
    }//GEN-LAST:event_txtDatabaseKeyTyped

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            txtPass.requestFocus();
        }
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            btnConectar.requestFocus();
        }
    }//GEN-LAST:event_txtPassKeyTyped

    private void cbTipoPersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoPersonaKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            cbDelimiter.requestFocus();
        }
    }//GEN-LAST:event_cbTipoPersonaKeyTyped

    private void cbDelimiterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbDelimiterKeyTyped
        int letra = evt.getKeyChar();
        if (letra == 10) {
            btnAbrirTxt.requestFocus();
        }
    }//GEN-LAST:event_cbDelimiterKeyTyped

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        if (jtContribuyente.getRowCount() > 0) {

            if (isExist()) {
                insertData();
            } else {
                int crear = JOptionPane.showConfirmDialog(this, "La tabla de contribuyentes no Existe, Desea crear la tabla?", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                if (crear == 0) {
                    crearTabla();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay Datos cargados para importar", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void creatArr() {
        String delimiter = null;
        switch (cbDelimiter.getSelectedIndex()) {
            case 0:
                delimiter = "|";
                break;
            case 1:
                delimiter = "\t";
                break;
        }

        BufferedReader br;
        try {
            br = new BufferedReader( new InputStreamReader(new FileInputStream(ruta.getText()), "UTF-8"));
            
            String line = br.readLine();
            while (line != null) {
                String[] rowfields = line.split("[" + delimiter + "]+");

                if (!rowfields[0].equals("RUC")) {
                    c++;
                    String ruc = rowfields[0];
                    String razon = rowfields[1];
                    String dv = rowfields[2];
                    switch (cbTipoPersona.getSelectedIndex()) {
                        case 0:
                            modelo.addRow(new Object[]{ruc, dv, razon, "f"});
                            break;
                        case 1:
                            modelo.addRow(new Object[]{ruc, razon, dv, "j"});
                            break;
                    }

                }
                line = br.readLine();
            }
            cant.setText(String.valueOf(formato.format(c)));
        } catch (FileNotFoundException e) {
            // can be thrown when creating the FileReader/BufferedReader
            // deal with the exception
            JOptionPane.showMessageDialog(this, "Error al importar, verifique su Delimitador", "Error", JOptionPane.ERROR_MESSAGE);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al importar, verifique su Delimitador", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void conexion() {

        try {
            PGSimpleDataSource dataSource = new PGSimpleDataSource();
            dataSource.setServerNames(new String[]{txtHost.getText()});
            dataSource.setDatabaseName(txtDatabase.getText());
            dataSource.setPortNumbers(new int[]{Integer.parseInt(txtPort.getText())});
            dataSource.setUser(txtUser.getText());
            dataSource.setPassword(txtPass.getText());
            dataSource.setCurrentSchema("public");
            conexion = dataSource.getConnection();
            blockComponent();
            JOptionPane.showMessageDialog(this, "Success Connection in " + txtDatabase.getText() + "", "Success!", JOptionPane.INFORMATION_MESSAGE);
            cbTipoPersona.requestFocus();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Fail Connection in " + txtDatabase.getText() + "", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validar() {
        if (txtHost.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El Host", "Error", JOptionPane.WARNING_MESSAGE);
            txtHost.requestFocus();
            return false;
        }
        if (txtPort.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El puerto de la BD", "Error", JOptionPane.WARNING_MESSAGE);
            txtPort.requestFocus();
            return false;
        }
        if (txtDatabase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El ingrese el Nombre de la BD", "Error", JOptionPane.WARNING_MESSAGE);
            txtDatabase.requestFocus();
            return false;
        }
        if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El password del usuario de la BD", "Error", JOptionPane.WARNING_MESSAGE);
            txtPass.requestFocus();
            return false;
        }
        if (txtUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El Usuario de la BD", "Error", JOptionPane.WARNING_MESSAGE);
            txtUser.requestFocus();
            return false;
        }
        return true;
    }

    private void blockComponent() {
        txtHost.setEnabled(false);
        txtUser.setEnabled(false);
        txtPass.setEnabled(false);
        txtDatabase.setEnabled(false);
        txtPort.setEnabled(false);
        btnExecute.setEnabled(true);

    }

    private boolean isExist() {
        Boolean existe = false;
        try {
            PreparedStatement ps = conexion.prepareStatement(ScriptSql.ISEXXIST);
            resultado = ps.executeQuery();
            resultado.next();
            existe = resultado.getBoolean(1);
        } catch (SQLException ex) {
            Logger.getLogger(Importar.class.getName()).log(Level.SEVERE, null, ex);
        }
        return existe;
    }

    private void crearTabla() {
        try {
            PreparedStatement ps = conexion.prepareStatement(ScriptSql.CREATE_TABLE);
            ps.execute();
            int crear = JOptionPane.showConfirmDialog(this, "La tabla fue creada con Exito, desea continuar con la importación", "Success!", JOptionPane.OK_CANCEL_OPTION);
            if (crear == 0) {
                insertData();
            }
        } catch (SQLException ex) {

        }
    }

    private void insertData() {
        Runnable miRunnable = () -> {
            try {
                iniciar();

            } catch (Exception e) {
            }
        };
        Thread hilos = new Thread(miRunnable);
        hilos.start();
    }

    private void iniciar() {
        guardar();
        hilo.start();
        hilo = null;
    }

    public void guardar() {
        btnClear.setEnabled(false);
        btnAbrirTxt.setEnabled(false);
        try {
            long cguardado = 0;

            PreparedStatement ps = conexion.prepareStatement(ScriptSql.INSERT_DATA);
            System.out.println(jtContribuyente.getRowCount());
            for (int in = 0; in < jtContribuyente.getRowCount(); in++) {

                cguardado++;
                ps.setString(1, jtContribuyente.getValueAt(in, 0).toString());
                ps.setInt(2, Integer.parseInt(jtContribuyente.getValueAt(in, 1).toString()));
                ps.setString(3, jtContribuyente.getValueAt(in, 2).toString());
                ps.setString(4, jtContribuyente.getValueAt(in, 3).toString());
                ps.addBatch();

                record.setText(String.valueOf(formato.format(in + 1)));
                hilo = new Cargar(getProgreso(), Integer.parseInt(cant.getText().replace(".", "")), Integer.parseInt(record.getText().replace(".", "")));

            }

            ps.executeBatch();

            JOptionPane.showMessageDialog(this, "Han sido Insertados: " + cguardado + " Registros", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            for (int i = jtContribuyente.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            c = 0;
            ruta.setText("");
            cant.setText("0");
            record.setText("0");
            Progreso.setValue(0);
            Progreso.setString("0%");
            btnClear.setEnabled(true);
            btnAbrirTxt.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Importar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public javax.swing.JProgressBar getProgreso() {
        return Progreso;
    }

    /**
     * @param Progreso the Progreso to set
     */
    public void setProgreso(javax.swing.JProgressBar Progreso) {
        this.Progreso = Progreso;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progreso;
    private javax.swing.JButton btnAbrirTxt;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnExecute;
    private javax.swing.JTextField cant;
    private javax.swing.JComboBox<String> cbDelimiter;
    private javax.swing.JComboBox<String> cbTipoPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jtContribuyente;
    private javax.swing.JDialog modal;
    private javax.swing.JTextField record;
    private javax.swing.JTextField ruta;
    private javax.swing.JFileChooser seleccionador;
    private javax.swing.JDialog selector;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtHost;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
